# Generated by Django 4.2.4 on 2023-09-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_lesson_vido_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='vido_url',
            new_name='video_url',
        ),
    ]
