# Generated by Django 4.2.4 on 2023-09-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_alter_subscription_course_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='owner',
        ),
    ]
