# Generated by Django 4.2.4 on 2023-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='session',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='сессия для оплаты'),
        ),
    ]
