# Generated by Django 4.2.4 on 2023-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_payments_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплата'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплата'),
        ),
    ]
