# Generated by Django 4.2.4 on 2023-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_remove_course_is_paid_remove_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления'),
        ),
    ]
